### PR TITLE
New i_am()

### LINKED ISSUE #27: assert_here()
It would be interesting to consider an `assert_here()` function.

Inspired by this [Twitter conversation](
https://twitter.com/emilelatour/status/1033019785087315968) with Emile Latour (@emilelatour).

Problem: *you* use Projects and the here package and life is awesome. But your *collaborator* still clicks on an Rmd in the Finder and it just opens in RStudio, in whatever Project (or non-Project) they happen to have open. Now all the path-building code doesn't work as planned when they run chunks interactively (knitting the whole document still works fine for them).

If you want to make a `.R` or `.Rmd` file more resilient to this and you feel like the Project's name is pretty stable, you could put `here::assert_here("PROJECT_NAME")` at the top as a way of raising an alarm when the workflow violates expectations.

`assert_here()` would be something like `assertthat::assert_that(identical(basename(here::here()), “PROJECT_NAME”))`.

### PR DESCRIPTION
**Pull request by krlmlr**
Intended usage: write `here::i_am("<project-relative path>/script.R")` at the beginning of your script, even before `library(here)`. It fails loudly and clearly if the current working directory is not a subdirectory of the anticipated project root.

A few things I like about this approach:

- Testing logic relies entirely on rprojroot, no own logic
- It solves the issue of changing here's notion of the project root without compromising on the idea of project-based workflows (#19, #24, #41)
- We can work on an upgrade path to nudge users to always declare their files in here 2.0.0 or 3.0.0
- `here::i_am()` seems like the logical answer to {whereami}

Closes #27.

### CODE REVIEW

**Comment by yonicd** [comment]
I haven’t tried this implementation yet, but does the user have to put `i_am` in files for this to work? The benefit of {whereami} was to do that wo forcing the user to leave breadcrumbs in their files. Ie whereami doesn’t need any help to figure out where the src of functions are located on disk.

**Comment by krlmlr** [comment]
Yes, users are expected to call `i_am()` . It uses a different approach -- whereami tries to find, `here::i_am()` declares. It's explicit, and very robust.

I wonder if these approaches can be combined? Are there situations where {whereami} gives surprising results?

**Comment by krlmlr** [comment]
Read more at https://here.r-lib.org/articles/here.html.

**Comment by yonicd** [comment]
whereami has been persistent in finding the right paths, including in rmds.

The motivation and goal of whereami was to be passive for adding src location footnotes to report plot/tables or debugging reactivity in shiny (@colinfay). 

From what i can gather (so far) it returns the same result for what i_am is trying to do.

I tried to stay away from forcing the users to add lines of code.

**Comment by yonicd** [comment]
assuming a file directory structure 

```r
> fs::dir_tree()
.
├── LICENSE
├── README.md
├── events.Rmd
├── events.html
├── gha_r_tutorial.Rproj
└── skeleton.Rmd
```

and the `skeleton.Rmd` file 

````
---
title: "Skeleton"
author: "Jonathan Sidi"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
here::i_am('skeleton.Rmd')
whereami::whereami()
whereami::whereami(path_expand = TRUE)
dirname(whereami::whereami(path_expand = TRUE))
```
````

the output from whereami calls give

```r
> whereami::whereami()
── Running From: ./skeleton.Rmd ────────────────────────────────────────────────────
> whereami::whereami(path_expand = TRUE)
── Running From: /Users/yonis/projects/gha_r_tutorial/skeleton.Rmd ─────────────────
> dirname(whereami::whereami(path_expand = TRUE))
[1] "/Users/yonis/projects/gha_r_tutorial"
```

`here::i_am('skeleton.Rmd')` gives the same output

```r
here::i_am('skeleton.Rmd')
here() starts at /Users/yonis/projects/gha_r_tutorial
```

<details closed>
<summary> <span title='Click to Expand'> session info </span> </summary>

```r

─ Session info ─────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-11-15                  

─ Packages ─────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                          
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                  
 cli           2.1.0      2020-10-12 [1] CRAN (R 3.6.3)                  
 clipr         0.7.0      2019-07-23 [1] CRAN (R 3.6.0)                  
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                  
 desc          1.2.0.9000 2020-09-28 [1] Github (r-lib/desc@c175259)     
 details       0.2.1      2020-01-12 [1] local                           
 fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.0)                  
 fs            1.4.1      2020-04-04 [1] CRAN (R 3.6.3)                  
 glue          1.4.2      2020-08-27 [1] CRAN (R 3.6.2)                  
 here          1.0.0.9000 2020-11-15 [1] Github (r-lib/here@93c699d)     
 httr          1.4.2      2020-07-20 [1] CRAN (R 3.6.2)                  
 jsonlite      1.7.1      2020-09-07 [1] CRAN (R 3.6.2)                  
 knitr         1.30       2020-09-22 [1] CRAN (R 3.6.2)                  
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                  
 png           0.1-7      2013-12-03 [1] CRAN (R 3.6.0)                  
 R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.0)                  
 rprojroot     2.0.2.9000 2020-11-15 [1] Github (r-lib/rprojroot@0878c64)
 rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.1)                  
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                  
 whereami      0.1.9      2020-09-24 [1] local                           
 withr         2.3.0      2020-09-22 [1] CRAN (R 3.6.2)                  
 xfun          0.17       2020-09-09 [1] CRAN (R 3.6.2)                  
 xml2          1.3.0      2020-04-01 [1] CRAN (R 3.6.2)                  

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

```

</details>
<br>

**Comment by krlmlr** [comment]
Thanks. What happens if `skeleton.Rmd` lives in a subdirectory?

**Comment by yonicd** [comment]
whereami returns the path regardless. 

Same logical is checked:

`grepl(here::here(),whereami::whereami(path_expand = TRUE))`

**Comment by krlmlr** [comment]
Yes, but how do we know what the project root is?

**Comment by yonicd** [comment]
That isn’t what whereami tries to solve. 

You can use rprojroot or here to query that (which seems to be happening already in i_am)

I am saying that you are forcing the user to give information that can be ascertained wo user intervention or making them supply you a breadcrumb for i_am to work.

**Comment by krlmlr** [comment]
We can think about supporting `here::i_am()` without arguments, using the auto-discovered path from whereami and existing root criteria.

**Comment by yonicd** [comment]
Great. thanks.

If you need any help bridging any gaps let me know.

**Pull request merged**
